version: '2'
services:
  composer:
    container_name: composer.forum
    build:
      context: ./
      dockerfile: ./.docker/build/php-composer.dockerfile
    working_dir: /app
    user: application
    volumes:
      - .:/app
      - $HOME/.composer:/home/application/.composer
    links:
      - db

  cli:
    container_name: cli.forum
    build:
      context: ./
      dockerfile: ./.docker/build/php-cli.dockerfile
    working_dir: /app
    user: application
    volumes:
      - .:/app
    links:
      - db

  app:
    container_name: app.forum
    build:
      context: ./
      dockerfile: ./.docker/build/php-fpm.dockerfile
    working_dir: /app
    user: www-data
    volumes:
      - .:/app
      - ./.docker/configs/php-fpm/www.conf:/etc/php/7.1/fpm/pool.d/www.conf
    restart: always
    links:
      - db

  nginx:
    container_name: nginx.forum
    image: "nginx:alpine"
    ports:
      - "80:80"
    volumes:
      - ./.docker/configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    restart: always
    links:
      - app

  node:
    container_name: nodejs.forum
    image: "node:latest"
    working_dir: /app
    volumes:
      - .:/app

  db:
    container_name: mysql.forum
    image: "mysql:latest"
    environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_DATABASE=forum
          - MYSQL_USER=forum
          - MYSQL_PASSWORD=forum
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
